# prettier-ignore
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cl-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - list
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - list
  - get
