apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
    last: final
    author: abdulaziz
  name: nginx2
  namespace: abdulaziz
spec:
  containers:
    - image: nginx
      name: nginx2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
